### ISSUE TITLE
如何从SetTimeLineUI获取AdListView

### ISSUE THREAD

**Issue by AlexGeller** [KingZD/WxDemo#2]
![image](https://user-images.githubusercontent.com/5525760/59736219-58d56400-928b-11e9-8db9-9c88e0cf8702.png)

请问你是如何从代码中获取到com.tencent.mm.plugin.sns.ui.bb这个类型的？

**Comment by KingZD** [comment]
把微信反编译的 代码导入Android studio 然后通过Android studio的 代码关联功能 反向查找 也就是，alt+鼠标左键 点击代码关联部，这个是逆向思维，有时候需要大胆猜测，然后小心实践，找到相关的 代码后我都会 写点xp代码进行调试
