### ISSUE TITLE
您好，想咨询您在看雪微信分析帖子中的一些问题

### ISSUE THREAD

**Issue by Forgo7ten** [KingZD/WxDemo#3]
跟着您的帖子分析了一下微信，目前看到了帖子二，虽然说类以及结构已经不相同了，但方法和思路还是给了我很大启发。
![unload](https://user-images.githubusercontent.com/57509907/129472864-eb0d3a89-8e08-4664-aab4-27da3e03b493.png)
想问一下您帖子中这个工具是什么呢？
另外能否留一个联系方式方便请教呢。

**Comment by KingZD** [comment]
> 跟着您的帖子分析了一下微信，目前看到了帖子二，虽然说类以及结构已经不相同了，但方法和思路还是给了我很大启发。
> ![unload](https://user-images.githubusercontent.com/57509907/129472864-eb0d3a89-8e08-4664-aab4-27da3e03b493.png)
> 想问一下您帖子中这个工具是什么呢？
> 另外能否留一个联系方式方便请教呢。

非常抱歉，现在才注意到，我使用的是Android studio自带的工具 tools->layout inspector.   您也可以在第四篇可以到我分析的全过程
